117 render position force data
cs481-ekh/f22-viz-kids pull request #118
Opened 2022-10-10 22:59 UTC by wkenny80

2022-10-10 23:48 UTC, vpzomtrrfrt requested changes

2022-10-10 23:48 UTC, vpzomtrrfrt commented on src/RenderView.tsx
> +	 }, []);
this line (and several others) have an extra space at the start that shouldn't be there

2022-10-10 23:48 UTC, vpzomtrrfrt commented on src/RenderView.tsx
> +		   if (!pos||isNaN(pos.x)||isNaN(pos.y)||isNaN(pos.z)||(pos.x===0&&pos.y===0&&pos.z===0)) {
I don't like this but that's on the parser side and we can deal with it later

2022-10-11 15:05 UTC, PTLux1517 approved these changes
As Colin mentioned, there are some whitespace issues, but we are getting close to the end of sprint 2. I plan on doing some refactoring in sprint 3 and can clean this up too if it's still there.

2022-10-12 01:38 UTC, closed without merging