Closes #63
cs481-ekh/f22-viz-kids pull request #76
Opened 2022-09-27 15:31 UTC by javitrejo14

2022-09-27 19:54 UTC, vpzomtrrfrt requested changes
this will need to be a change to the App component, not a separate file

2022-09-28 20:09 UTC, wkenny80 approved these changes

2022-09-29 15:19 UTC, PTLux1517 commented
Changes have been moved to the App component in PR #86. This can be closed without merge, unless we want to keep the prototype work in a `prototype` directory within `src`, in which case those changes could be added here and reviewed.

2022-09-29 19:43 UTC, javitrejo14 commented
Closed this pull request because the code I wrote (mainPage.html) is no longer needed.

2022-09-29 19:43 UTC, closed without merging